### ISSUE TITLE
Can't load sample dataset 

### ISSUE THREAD

**Issue by wendy321** [yiq/gene.iobio.local#2] opened 2016-12-20 17:14 UTC
Hello Yi Qiao,

Sorry to bother you. I am new to install all of these and GitHub is the only way that I can find to contact you. 

(Question 1) I met a problem after installing the gene.iobio (master branch) locally. 

When I selected "Variants" -> "Platinum Trio" -> "https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz",
it keeps "Accessing file header" for over 30 mins.

But it is fine for "Alignments"  -> "Platinum Trio" -> "https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam".

ps. I change the port of docker-compose.yml 
      from     - "80:80"   to     - "8080:80"
      because 80 has already allocated to apache2.

(Question 2) Is it possible to customized the filtering  function by my own? 

I have a lot of gene samples and can filter them based on their attributes though some javascript library, but I am not sure whether I can integrate it with gene.iobio libraries or not? It seems like the gene.iobio libraries are all developed as web services.

Thank you & Best Regards,

Wendy
----------------------------------------------------------------------
Web application engineer I at UTSW Medical Center

**Comment by yiq** [comment] 2016-12-20 22:14
Hi Wendy

  Thanks for your interest in gene.iobio. I think the issue with the vcf header not loading correctly might be caused by the port number mismatch. When you run the 'start.sh' script, you need to give it the hostname and the port number if it's not 80 (e.g. $ ./start.sh gene.example.org:8080). http://hostname:port/ is then used to construct backend URLs the frontend would then call. I'd suggest you give it a try, and see if it works out better. It the problem still persists, we can further troubleshoot from there.

  As for custom filtering functions, I think it's better if you discuss it at the gene.iobio repository (https://github.com/tonydisera/gene.iobio). 

Let me know how it goes

**Comment by wendy321** [comment] 2016-12-21 00:07
Hi Yi Qiao,
Thank you for your help. I have ran $ sudo ./start.sh hostname:8080, but still got the same issue. 
Wendy

**Comment by yiq** [comment] 2016-12-21 00:11
Hmm... can you run the website again with the browser debugger open, and send me the console logs

**Comment by wendy321** [comment] 2016-12-21 15:28
No problem. Here is the console logs.
![gene_iobio_error_msg](https://cloud.githubusercontent.com/assets/8990321/21394820/c58ef772-c75f-11e6-98f9-88834e8a7d4f.jpg)

**Comment by yiq** [comment] 2016-12-23 06:13
sorry I was busy for a while

Would you mind try this: edit 'globalsDeployment.js.tmpl' at the root directory of the repository by going to line 19 (https://github.com/yiq/gene.iobio.local/blob/master/globalsDeployment.js.tmpl#L19) and change it to false. It should be false as the default. I must have accidentally committed the wrong value.

**Comment by yiq** [comment] 2017-01-08 20:03
Hi

  based on the fact that you created tonydisera/gene.iobio#506, I take it that you have successfully deployed gene.iobio locally. I'm closing this issue for now. If you still experience deployment-related issues, feel free to create a new issue.

**Closed as completed by yiq** 2017-01-08 20:03 UTC

**Comment by wendy321** [comment] 2017-01-09 20:59
Hi,
I successfully deployed the website which is downloaded from tonydisera/gene.iobio master branch. Thank you for your previous help.

**Comment by yiq** [comment] 2017-01-10 06:34
You are welcome. keep in mind that if you are only hosting
tonydisera/gene.iobio locally, you are only serving the frontend (the web
app that runs in user's browsers) from your own hardware. All requests,
such as annotate variants, are going to the backend that we maintain. We
often bring down the backend for maintenance / upgrade, which is also often
backward incompatible. If you want to host the backend on your own
hardware, so that you can have greater control over maintenance cycle, I'd
still suggest that you use this repository as your way of deployment. I'd
be happy to work with you on this. Let me know

**Comment by wendy321** [comment] 2017-01-10 17:40
(1) Great! We want to host the backend on our own machine and have better control on maintenance.
(2) There're some problems in both tonydisera/gene.iobio master and this repository:
      (a) (this repository) I still can't load Platinum Trio for Variants in my local machine. 
      (b) (tonydisera/gene.iobio master) My colleagues can't load Platinum Trio for Variants when they linked to the website deployed on my local machine through organization's internal wifi. But I can when I access the website using my local machine.
      May the proxy be the issue for (a) and (b)?
      (c)  (this repository and tonydisera/gene.iobio master) My colleagues said the website doesn't support HG38 data. I am not sure where can I modify the code for reading the HG38.
      (d) The project investor has other requirements. I think we may discuss them with Tony Disera in the conference call. Hope my manager want to have a conference call, too!

**Comment by wendy321** [comment] 2017-01-10 19:00
I am really thankful for your help!
Could you help me to host the backend on my own machine? 
Are there any prerequisites for the hardware? 
Do you know anything about how to support HG38 data? My supervisor seems rush on supporting HG38 and hopes I can do it. She thinks it is the first priority.
